version: '3.7'

services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-test
        volumes:
            - ./src:/app/src
        ports:
            - '3031:3031'
        command: npm run test
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-dev
        volumes:
            - ./src:/app/src
        ports:
            - '3030:3030'
            - '8181:8181'
        command: npm run dev
