version: '3.7'

services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-test
        env_file: .env.example
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
        ports:
            - '$PORT:$PORT'
        command: npm run test
