version: '3.7'

services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-test
        environment:
            - PORT=3000
        volumes:
            - .:/app
        ports:
            - '$PORT:$PORT'
        command: npm run test
