version: '3.7'

services:
    dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-dev
        volumes:
            - .:/app
        environment: 
            - PORT=$PORT
        ports:
            - '$PORT:$PORT'
        command: npm run dev:docker
