version: '3.7'

services:
    test:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-test
        environment:
            - PORT=3001
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
            - ./jest.config.ts:/app/jest.config.ts
            - ./tsconfig.json:/app/tsconfig.json
        ports:
            - '3001:3001'
        command: npm run test
